apiVersion: apps/v1
kind: Deployment
metadata:
  name: compound-interest-api
  labels:
    app: compound-interest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compound-interest-api
  template:
    metadata:
      labels:
        app: compound-interest-api
    spec:
      containers:
      - name: compound-interest-api
        image: compound-interest-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: compound-interest-api-service
spec:
  selector:
    app: compound-interest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer 